### ISSUE TITLE
Not creating App_Plugins folder

### ISSUE THREAD

**Issue by RyanWF73** [huwred/RTEStyleFormatter#1]
Not sure if this is an issue on my end. 

Installed this package to a .net8 Umbraco 13.3.2 website and noticed it just didn't really seem to be doing anything on build or clean. No messages are being triggered at all on build / clean and no App_Plugins folder is created. 
Nugets didn't seem to connect to the .targets file as it's not in the imports section like other packages. 

Tried again on a .net7 Umbraco 11.4.2 website and it's the same story. 
Tried installing through NuGet direct and through the PM console commands for the marketplace.

Tried restarting VS, Admin and clearing NuGet Cache to no success. 

Any idea on what the issue could be?

**Comment by huwred** [comment]
Hi, I will check and get back to you

**Comment by huwred** [comment]
Hi, discovered a couple  of issues, have released a new version which should resolve it

[Umbraco.Community.RTEStyleFormatter 1.0.2](https://www.nuget.org/packages/Umbraco.Community.RTEStyleFormatter/1.0.2)

**Comment by RyanWF73** [comment]
That's fixed it! Many thanks!

Just as an aside, noticed it saves the appsettings.json with the encoding Unicode (UTF-8) with signature. 
Is this necessary or could it be possible to stick to without signature? As it's touched a few other lines during the process, like ValidElements or for us the PreviewBadge

Don't think it'll be a deal breaker but thought i'd ask anyways!

**Comment by huwred** [comment]
HI,

There is no specific reason, I will remove the encoding. I have also worked out how to get it saved without all the pointless escaping so will roll that into a new version, should be ready tomorrow

**Comment by huwred** [comment]
I have posted an update which removes the file encoding and uses different escaping when writing back to appsettings

https://www.nuget.org/packages/Umbraco.Community.RTEStyleFormatter/1.0.3

**Comment by RyanWF73** [comment]
Hey thanks for that! Just got round to updating and it's looking nice now. #H5YR
